# Change these first
owner: okj579 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Cloud
    url: https://cloud.okj.name
  - name: bill
    url: https://bill.okj.name
  - name: jack
    url: https://jack.okj.name

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
